#!/bin/bash

upgrade_homebrew() {
    brew bundle --no-lock --file ~/.config/homebrew/Brewfile
    brew update
    brew upgrade
}

upgrade_apt() {
    system_type=$(uname -s)
    if [[ "${system_type}" == "Linux" ]]; then
        sudo apt-get --yes update
        sudo apt-get --yes upgrade
    fi
}

install_asdf_tools() {
    while read line; do
        plugin=$(echo "${line}" | cut -d' ' -f1)
        asdf plugin add "${plugin}"
    done < ~/.tool-versions
    asdf install
}

install_libraries() {
    # Python
    pip install --upgrade pip
    pip install -r ~/.config/lang/python/requirements.txt

    # Rust
    cargo install aoc-cli
    cargo install --path ~/.config/weather
    asdf reshim rust

    # Node
    npm install -g pnpm
    npm install -g neovim

    # OCaml
    opam init --no
    opam update
    opam upgrade --yes
}

setup_repos() {
    /bin/bash -c ~/.config/yadm/setup-repos
}

upgrade_homebrew
upgrade_apt
install_asdf_tools
install_libraries
setup_repos
