#!/bin/sh

install_homebrew() {
    if ! command -v brew >/dev/null 2>&1; then
        echo "Installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    echo "Updating Homebrew bundle"
    brew bundle --global
}

install_asdf_tools() {
    while read line; do
        plugin=$(echo "${line}" | cut -d' ' -f1)
        asdf plugin add "${plugin}"
    done < ~/.tool-versions
    asdf install
}

install_libraries() {
    cargo install rust-script
    cargo install stylua
    asdf reshim rust
    npm install -g eslint
    npm install -g prettier
}

install_homebrew
install_asdf_tools
install_libraries
/bin/bash -c ~/.config/yadm/setup_repos
