#!/bin/sh

install_homebrew() {
    if ! command -v brew >/dev/null 2>&1
    then
        echo "Installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    echo "Updating Homebrew bundle"
    brew bundle --global
}

install_homebrew
