# Programming Related
brew "bat"
brew "bison"
brew "curl"
brew "fd"
brew "fzf"
brew "git"
brew "git-delta"
brew "jq"
brew "just"
brew "lazygit"
brew "libsodium"
brew "mise"
brew "ninja"
brew "pandoc"
brew "pre-commit"
brew "ripgrep"
brew "tlrc"
brew "tmux"
brew "wget"
brew "yadm"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Terminals
cask "alacritty"
cask "ghostty"
cask "kitty"
cask "wezterm"

# Fonts
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "font-symbols-only-nerd-font"

# General
brew "cairo"
brew "cmake"
brew "coreutils"
brew "gpatch"
brew "oath-toolkit"
brew "pass"
brew "pkg-config"
brew "xz"

# Editors
brew "neovim"
brew "vim"
cask "intellij-idea-ce"
cask "mactex"
cask "sublime-text"
cask "visual-studio-code"

# Productivity Apps
cask "discord"
cask "elgato-stream-deck"
cask "google-chrome"
cask "libreoffice"
cask "private-internet-access"
cask "rectangle"
cask "vlc"

# Other
brew "stockfish"
