" no bell
set belloff=all

" disable viminfo
set viminfofile=NONE

" enable syntax highlighting
syntax on

" line number
set number
set relativenumber

" search
set ignorecase
set smartcase

" wait time for detecting changes
set updatetime=250

" split to right / below by default
set splitright
set splitbelow

" indentation
set smartindent

" tab / space
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" keep context in view
set scrolloff=8
set sidescrolloff=8

" use system clipboard
set clipboard=unnamedplus
