" general
set belloff=all
set clipboard=unnamedplus
set viminfofile=NONE
syntax on

" ui
set number
set relativenumber
set scrolloff=8
set sidescrolloff=8
set splitbelow
set splitright

" editing
set expandtab
set ignorecase
set shiftwidth=4
set smartcase
set smartindent
set softtabstop=4
set tabstop=4
set updatetime=250
