[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.6", features = ["derive"] }
ipgeolocate = "0.3.5"
itertools = "0.11.0"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
textplots = "0.8.4"
tokio = { version = "1.32.0", features = ["full"] }
