return {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    event = { 'BufReadPre', 'BufNewFile' },
    dependencies = {
        'nvim-treesitter/nvim-treesitter-context',
        'nvim-treesitter/nvim-treesitter-textobjects',
    },
    config = function()
        ---@diagnostic disable-next-line: missing-fields
        require('nvim-treesitter.configs').setup({
            ensure_installed = {
                'bash',
                'c',
                'c_sharp',
                'cmake',
                'cpp',
                'css',
                'css',
                'dart',
                'dockerfile',
                'go',
                'groovy',
                'html',
                'java',
                'javascript',
                'jq',
                'jsdoc',
                'json',
                'kotlin',
                'latex',
                'lua',
                'make',
                'markdown',
                'markdown_inline',
                'ocaml',
                'python',
                'rust',
                'scala',
                'scss',
                'svelte',
                'terraform',
                'toml',
                'typescript',
                'vue',
                'yaml',
                'zig',
            },
            highlight = { enable = true },
            indent = { enable = true },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = '<c-v>',
                    node_incremental = 'v',
                    node_decremental = 'V',
                    scope_incremental = false,
                },
            },
        })
    end,
}
