- name: Setup 
  hosts: localhost

  tasks:
  - name: Install dependencies
    apt:
      update_cache: true
      update_cache_retries: 1
      state: latest
      name:
        - bubblewrap
        - build-essential
        - gcc
        - git
        - latexmk
        - libbz2-dev
        - libffi-dev
        - liblzma-dev
        - libncursesw5-dev
        - libreadline-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
        - libxmlsec1-dev
        - llvm
        - make
        - texlive
        - texlive-xetex
        - tk-dev
        - wget
        - wl-clipboard
        - xz-utils
        - zlib1g-dev
    become: true
    when: ansible_facts['os_family'] == 'Debian'
  - name: Print Darwin
    debug:
      msg: Hello Darwin
    when: ansible_facts['os_family'] == 'Darwin'
