[[language]]
name = "bash"

[[language]]
name = "go"

[[language]]
name = "java"

[[language]]
name = "lua"

[[language]]
name = "ocaml"

[[language]]
name = "python"
language-servers = [ "basedpyright" ]

[language-server.basedpyright.config.basedpyright.analysis]
diagnosticMode = "workspace"

[language-server.basedpyright.config.basedpyright.analysis.diagnosticSeverityOverrides]
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnusedCallResult = false

[[language]]
name = "ruby"
language-servers = [ "ruby-lsp" ]

# TODO: remove after https://github.com/helix-editor/helix/pull/12511
[language-server.ruby-lsp]
command = "ruby-lsp"

[[language]]
name = "rust"

[[language]]
name = "zig"

[language-server.zls.config]
warn_style = true
skip_std_references = true
