[[language]]
name = "python"
language-servers = ["basedpyright"]

[language-server.basedpyright.config.basedpyright.analysis]
diagnosticMode = "workspace"

[language-server.basedpyright.config.basedpyright.analysis.diagnosticSeverityOverrides]
reportAny = false
reportExplicitAny = false
reportMissingTypeStubs = false
reportUnusedCallResult = false

[language-server.jdtls]
command = "bash"
args = [
  "-c",
  "jdtls --jvm-arg=-javaagent:${MASON_HOME}/packages/jdtls/lombok.jar",
]

[language-server.zls.config]
warn_style = true
skip_std_references = true
