[[language]]
name = "bash"

[[language]]
name = "go"

[[language]]
name = "java"

[[language]]
name = "lua"

[[language]]
name = "ocaml"

[[language]]
name = "python"

[[language]]
name = "rust"

[[language]]
name = "zig"
