[[language]]
name = "bash"

[[language]]
name = "go"

[[language]]
name = "java"

[[language]]
name = "lua"

[[language]]
name = "ocaml"

[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "rust"

[[language]]
name = "zig"

[language-server.zls.config]
warn_style = true
skip_std_references = true
